merged with latest Soar changes (including post 8.5.0 release stuff)

diff --git a/OldSoar/branches/rmarinie_emotion/soar/make-soar b/OldSoar/branches/rmarinie_emotion/soar/make-soar
--- a/OldSoar/branches/rmarinie_emotion/soar/make-soar
+++ b/OldSoar/branches/rmarinie_emotion/soar/make-soar
@@ -1,22 +1,46 @@
-#!/bin/csh
+#!/bin/sh
+# $Id$
+
 pushd kernel
 chmod u+x ./configure
 
-# a more verbose version, if everything isn't automatically found...
-#./configure --with-tcl-lib-dir=/usr/local/lib --with-tk-lib-dir=/usr/local/lib
-
 ./configure
+if [ $? == "1" ]; then
+  echo
+  echo "!!! Couldn't configure kernel (check for error messages above)."
+  exit
+fi
 
 make
 popd
 pushd tcl-interface
 chmod u+x ./configure
 
-# a more verbose version, if everything isn't automatically found...
-#./configure --prefix=../.. --with-tcl-lib-dir=/usr/local/lib --with-tcl-doc-dir=/usr/tcl/man --with-tk-lib-dir=/usr/local/lib  --with-kernel=../kernel
+./configure --prefix=../.. --with-kernel=../kernel
+if [ $? == "1" ]; then
 
-./configure --with-preferred-tcl-version=8.3 --with-preferred-tk-version=8.3
+  echo
+  echo "*** Couldn't find tcl/tk in usual location, trying again with ActiveTcl defaults..."
+  echo
 
+  ./configure --prefix=../.. --with-tcl-lib-dir=/usr/local/ActiveTcl/lib \
+  --with-tcl-doc-dir=/usr/local/ActiveTcl/man --with-tk-lib-dir=/usr/local/ActiveTcl/lib  \
+  --with-kernel=../kernel
+  if [ $? == "1" ]; then
+    echo
+    echo "!!! Couldn't configure tcl-interface (check for error messages above)."
+    exit
+  fi
+  
+  echo
+  echo "*** Since the Tcl binaries are not in the default location, you will"
+  echo "*** need to change the first line in init-soar.tcl to the following:"
+  echo "*** #!/usr/local/ActiveTcl/bin/wish"
+  echo 
+  
+fi
 make
 cp  libsoar8.5* ../library
 popd
+
+chmod u+x ./init-soar.tcl
